DigitalStore/Areas/Admin/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigitalStore.Models;
using PagedList;
using PagedList.Mvc;

namespace DigitalStore.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        MyDataDataContext db = new MyDataDataContext();
        // GET: Admin/DonHang
        public ActionResult Index(int?page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;
            return View(db.PHIEUMUAs.ToList().OrderBy(n => n.NGAYDAT).ToPagedList(pageNum, pageSize));
        }
        public ActionResult ChiTietDonHang(int id)
        {
            //Lấy ra đối tượng sách theo mã
            PHIEUMUA donhang = db.PHIEUMUAs.SingleOrDefault(n => n.MAPHIEUMUA == id);
            ViewBag.MaPhieuMua = donhang.MAPHIEUMUA;
            if (donhang == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(donhang);
        }
    }
}

DigitalStore/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigitalStore.Models;
using PagedList;
using PagedList.Mvc;

namespace DigitalStore.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        MyDataDataContext db = new MyDataDataContext();
        // GET: Admin/HomeAdmin
        public ActionResult Index(int? page)
        {
            // Lấy ra tổng số các đơn đặt hàng đang có trong database - tổng số đơn hàng 
            ViewBag.DonHang = db.PHIEUMUAs.Count();
            // Lấy ra tổng số tiền các đơn hàng - lợi nhuận
            ViewBag.LoiNhuan = db.HOADONs.Sum(model => model.TONGTIEN);
            // Lấy ra tổng số lượng các user khách hàng đang có trong database - tổng số tài khoản hiện tại
            ViewBag.NguoiDung = db.NGUOIDUNGs.Where(model => model.MAQUYEN == 0).Count();
            //// Lấy số lượng người truy cập từ Application đã tạo
            //ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            // Lấy ra tổng số sản phẩm đang có trong database
            ViewBag.SanPham = db.SANPHAMs.Count();

            int pageNum = (page ?? 1);
            int pageSize = 7;
            return View(db.PHIEUMUAs.ToList().OrderBy(n => n.NGAYDAT).ToPagedList(pageNum, pageSize));
        }
    }
}

DigitalStore/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigitalStore.Models;
using PagedList;
using PagedList.Mvc;

namespace DigitalStore.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        MyDataDataContext db = new MyDataDataContext();
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 7;
            return View(db.SANPHAMs.ToList().OrderBy(n => n.NGAYCAPNHAT).ToPagedList(pageNum, pageSize));
        }
        public ActionResult ChiTietSanPham(int id)
        {
            //Lấy ra đối tượng sách theo mã
            SANPHAM sanpham = db.SANPHAMs.SingleOrDefault(n => n.MASANPHAM == id);
            ViewBag.MaSanPham = sanpham.MASANPHAM;
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanpham);
        }
        public ActionResult ThemSanPham()
        {
            //đưa dữ liệu vào dropdownList
            //Lấy ds từ table chủ đề, sắp xếp tăng dần theo tên chỉ đề
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs.ToList().OrderBy(n => n.TENNCCC), "MANCC", "TENNCCC");
            ViewBag.MaLoai = new SelectList(db.LOAIMAYs.ToList().OrderBy(n => n.TENLOAI), "MALOAI", "TENLOAI");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemSanPham(SANPHAM sanpham, FormCollection collection)
        {
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs.ToList().OrderBy(n => n.TENNCCC), "MANCC", "TENNCCC");
            ViewBag.MaLoai = new SelectList(db.LOAIMAYs.ToList().OrderBy(n => n.TENLOAI), "MALOAI", "TENLOAI");
            var E_tensanpham = collection["tensanpham"];
            var E_thongsokythuat = collection["thongsokythuat"];
            var E_anhsanpham = collection["HINH"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_giagiam = Convert.ToDouble(collection["giagiam"]);
            var E_soluongton = collection["soluongton"];
            var E_ngaycapnhat = DateTime.Now;
    
            //if (string.IsNullOrEmpty(E_tensanpham) || string.IsNullOrEmpty(E_thongsokythuat))
            //{
            //    ViewData["Error"] = "Don't empty!";
            //    return this.ThemSanPham();
            //}
            //else
            //{
                sanpham.TENSANPHAM = E_tensanpham.ToString();
                sanpham.THONGSOKYTHUAT = E_thongsokythuat;
                sanpham.HINH = E_anhsanpham;
                sanpham.GIABAN = E_giaban;
                sanpham.GIAGIAM = E_giagiam;
                sanpham.NGAYCAPNHAT = E_ngaycapnhat;

                sanpham.TRANGTHAI = 1;
                db.SANPHAMs.InsertOnSubmit(sanpham);
                db.SubmitChanges();
               
            //}
            return RedirectToAction("Index");
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images_product/" + file.FileName));
            return "Content/images_product/" + file.FileName;
        }
        public ActionResult SuaSanPham(int id)
        {
            SANPHAM sanpham = db.SANPHAMs.SingleOrDefault(n => n.MASANPHAM == id);
            if (sanpham == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs.ToList().OrderBy(n => n.TENNCCC), "MANCC", "TENNCCC");
            ViewBag.MaLoai = new SelectList(db.LOAIMAYs.ToList().OrderBy(n => n.TENLOAI), "MALOAI", "TENLOAI");
            return View(sanpham);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaSanPham(int id, FormCollection collection)
        {
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs.ToList().OrderBy(n => n.TENNCCC), "MANCC", "TENNCCC");
            ViewBag.MaLoai = new SelectList(db.LOAIMAYs.ToList().OrderBy(n => n.TENLOAI), "MALOAI", "TENLOAI");
            var E_sanpham = db.SANPHAMs.First(m => m.MASANPHAM == id);
            var E_tensanpham = collection["tensanpham"];
            var E_thongsokythuat = collection["thongsokythuat"];
            var E_anhsanpham = collection["anhsanpham"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_giagiam = Convert.ToDouble(collection["giagiam"]);
            var E_ngaycapnhat = DateTime.Now;


            E_sanpham.MASANPHAM = id;

                E_sanpham.TENSANPHAM = E_tensanpham;
                E_sanpham.THONGSOKYTHUAT = E_thongsokythuat;
                E_sanpham.HINH = E_anhsanpham;
                E_sanpham.GIABAN = E_giaban;
                E_sanpham.GIAGIAM = E_giagiam;
                E_sanpham.NGAYCAPNHAT = E_ngaycapnhat;

                UpdateModel(E_sanpham);
                db.SubmitChanges();
                return RedirectToAction("Index");             
        }
        public ActionResult Delete()
        {
            return View("Index");
        }
        [HttpPost]
        public ActionResult Delete (int id)
        {
            var E_sanpham = db.SANPHAMs.First(m => m.MASANPHAM == id);
            if (E_sanpham.MASANPHAM == id)
            {
                E_sanpham.TRANGTHAI = 0;
                db.SANPHAMs.DeleteOnSubmit(E_sanpham);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            } 
            return RedirectToAction("Index");
        }
    }
}

DigitalStore/Areas/Admin/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using DigitalStore.Models;

namespace DigitalStore.Areas.Admin.Controllers
{
    public class TaiKhoanController : Controller
    {
        MyDataDataContext db = new MyDataDataContext();
        // GET: Admin/TaiKhoan
        public ActionResult Index(int? page)
        {
            int pageNum = (page ?? 1);
            int pageSize = 10;
            return View(db.NGUOIDUNGs.Where(model => model.MAQUYEN != 0).ToList().ToPagedList(pageNum, pageSize));
        }
    }
}

DigitalStore/Areas/Admin/Views/Shared/Error401.cshtml
@{
	ViewBag.Title = "Error401";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutHomeAdmin.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			401 Error Page
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li><a href="#">Examples</a></li>
			<li class="active">401 error</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">

		<div class="error-page">
			<h2 class="headline text-red">401</h2>

			<div class="error-content">
				<h3><i class="fa fa-warning text-red"></i>Bạn không có quyền truy cập chức năng này</h3>

				<p>
					 <a href="https://localhost:44347/Admin">Quay về trang chủ</a> 
				</p>

				
			</div>
		</div>
		<!-- /.error-page -->

	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->

DigitalStore/Areas/Admin/Views/Shared/_LayoutHomeAdmin.cshtml
@using DigitalStore.Models
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Areas/Admin/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Areas/Admin/Content/css/sb-admin-2.min.css" rel="stylesheet">

    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' })</script>
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "HomeAdmin")">
                <div class="sidebar-brand-icon rotate-n-15">
                    @*<i class="fas fa-laugh-wink"></i>*@
                    <img src="~/Areas/Admin/Content/img/logo-login-removebg-preview.png" height="75px" width="75px" />
                </div>
                <div class="sidebar-brand-text mx-3">DigitalStore Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Tổng Quan -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "HomeAdmin")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Tổng Quan</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Danh Mục
            </div>

            <!-- Sản phẩm -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-camera"></i>
                    <span>Sản Phẩm</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Các thành phần:</h6>
                        <a class="collapse-item" href="@Url.Action("Index", "QLHangMay")">Quản lý hãng sản phẩm</a>
                        <a class="collapse-item" href="@Url.Action("Index", "QLLoaiMay")">Quản lý loại sản phẩm</a>
                        <a class="collapse-item" href="@Url.Action("Index", "SanPham")">Quản lý sản phẩm</a>
                    </div>
                </div>
            </li>

            <!-- Đơn hàng -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "DonHang")">
                    <i class="fas fa-fw fa-money-bill"></i>
                    <span>Đơn Hàng</span>
                </a>
            </li>

            <!-- Nhân Viên -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-user"></i>
                    <span>Tài Khoản Nhân Viên</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Các thành phần:</h6>
                        <a class="collapse-item" href="@Url.Action("Index", "TaiKhoan")">Quản lý tài khoản</a>
                        <a class="collapse-item" href="@Url.Action("Index", "PhanQuyen")">Phân quyền tài khoản</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>


        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @if (Session["TaiKhoanAdmin"] != null)
                                {
                                    NGUOIDUNG admin = (NGUOIDUNG)Session["TaiKhoanAdmin"];
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">@admin.HOVATEN</span>
                                }
                                <img class="img-profile rounded-circle"
                                     src="~/Areas/Admin/Content/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Thông tin cá nhân
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Cài đặt
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng xuất
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->

                <div class="container-fluid">

                    <div>
                        @RenderBody()
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Đăng Xuất?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Chọn "Đăng Xuất" bên dưới nếu bạn muốn kết thúc phiên hiện tại.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                    <a class="btn btn-primary" href="@Url.Action("Login", "LoginAdmin")">Đăng Xuất</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Areas/Admin/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Areas/Admin/Content/vendor/jquery-easing/jquery.easing.compatibility.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Areas/Admin/Content/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Areas/Admin/Content/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Areas/Admin/Content/js/chart-area-demo.js"></script>
    <script src="~/Areas/Admin/Content/js/chart-pie-demo.js"></script>

    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)
</body>
</html>